Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^planner4u/', include('planner4u.urls')),
    url(r'^admin/', admin.site.urls),
]

planner4u/urls.py
import planner4u.urls
from planner4u import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include


app_name = "planner4u"

urlpatterns = [
    url(r"^ministry/$", views.ministry, name="ministry"),

    url(r"^test/$", views.test, name="test"),

    url(r"^bhp-home/$", views.bhp_home, name="bhp-home"),
    url(r"^bif-home/$", views.bif_home, name="bif-home"),
    url(r"^home/$", views.home, name="home"),
    url(r"^wesi-home/$", views.wesi_home, name="wesi-home"),
    url(r"^wk-home/$", views.wk_home, name="wk-home"),
    url(r"^wl-home/$", views.wl_home, name="wl-home"),
    url(r"^wnpp-home/$", views.wnpp_home, name="wnpp-home"),
    url(r"^woa-home/$", views.woa_home, name="woa-home"),
    url(r"^wrz-home/$", views.wrz_home, name="wrz-home"),
    url(r"^wzn-home/$", views.wzn_home, name="wzn-home"),
    url(r"^wzp-home/$", views.wzp_home, name="wzp-home"),
    url(r"^zp-home/$", views.zp_home, name="zp-home"),
    url(r"^zuit-home/$", views.zuit_home, name="zuit-home"),

    url(r"^gkm-home/$", views.gkm_home, name="gkm-home"),
    url(r"^wb-home/$", views.wb_home, name="wb-home"),
    url(r"^wk2-home/$", views.wk2_home, name="wk2-home"),
    url(r"^wp-home/$", views.wp_home, name="wp-home"),
    url(r"^wrp-home/$", views.wrp_home, name="wrp-home"),

    url(r"^a-home/$", views.a_home, name="a-home"),
    url(r"^iod-home/$", views.iod_home, name="iod-home"),
    url(r"^polis-home/$", views.polis_home, name="polis-home"),
    url(r"^rl-home/$", views.rl_home, name="rl-home"),
    url(r"^rll-home/$", views.rll_home, name="rll-home"),
    url(r"^za-home/$", views.za_home, name="za-home"),
    url(r"^zswp-home/$", views.zswp_home, name="zswp-home"),

    url(r"^p-home/$", views.p_home, name="p-home"),
    url(r"^ssp-home/$", views.ssp_home, name="ssp-home"),
    url(r"^wok-home/$", views.wok_home, name="wok-home"),
    url(r"^za1-home/$", views.za1_home, name="za1-home"),
    url(r"^zklz-home/$", views.zklz_home, name="zklz-home"),
    url(r"^zp1-home/$", views.zp1_home, name="zp1-home"),

    url(r"^gkr-home/$", views.gkr_home, name="gkr-home"),
    url(r"^wbrl-home/$", views.wbrl_home, name="wbrl-home"),
    url(r"^wesll-home/$", views.wesll_home, name="wesll-home"),
    url(r"^wpr-home/$", views.wpr_home, name="wpr-home"),
    url(r"^wsa-home/$", views.wsa_home, name="wsa-home"),

    url(r"^wee-home/$", views.wee_home, name="wee-home"),
    url(r"^wesi-home/$", views.wesi_home, name="wesi-home"),
    url(r"^wkic-home/$", views.wkic_home, name="wkic-home"),

    url(r"^we-home/$", views.we_home, name="we-home"),
    url(r"^weg-home/$", views.weg_home, name="weg-home"),

    url(r"^wij-home/$", views.wij_home, name="wij-home"),
    url(r"^wis-home/$", views.wis_home, name="wis-home"),
    url(r"^wsr-home/$", views.wsr_home, name="wsr-home"),

    url(r"^waf-home/$", views.waf_home, name="waf-home"),
    url(r"^wep-home/$", views.wep_home, name="wep-home"),
    url(r"^wkm-home/$", views.wkm_home, name="wkm-home"),

    url(r"^sok-home/$", views.sok_home, name="sok-home"),
    url(r"^wg-home/$", views.wg_home, name="wg-home"),
    url(r"^wr-home/$", views.wr_home, name="wr-home"),
    url(r"^wrd-home/$", views.wrd_home, name="wrd-home"),
    url(r"^wrh-home/$", views.wrh_home, name="wrh-home"),
    url(r"^wte-home/$", views.wte_home, name="wte-home"),

    url(r"^wfn-home/$", views.wfn_home, name="wfn-home"),
    url(r"^wip-home/$", views.wip_home, name="wip-home"),
    url(r"^wkf-home/$", views.wkf_home, name="wkf-home"),
    url(r"^wksn-home/$", views.wksn_home, name="wksn-home"),
    url(r"^wkw-home/$", views.wkw_home, name="wkw-home"),
    url(r"^wm-home/$", views.wm_home, name="wm-home"),
    url(r"^wn-home/$", views.wn_home, name="wn-home"),
    url(r"^wnsr-home/$", views.wnsr_home, name="wnsr-home"),
    url(r"^wpe-home/$", views.wpe_home, name="wpe-home"),
    url(r"^wprpt-home/$", views.wprpt_home, name="wprpt-home"),
    url(r"^ww-home/$", views.ww_home, name="ww-home"),
    url(r"^wz-home/$", views.wz_home, name="wz-home"),
    url(r"^wzf-home/$", views.wzf_home, name="wzf-home"),

    url(r"^f-home/$", views.f_home, name="f-home"),
    url(r"^whg-home/$", views.whg_home, name="whg-home"),
    url(r"^wig-home/$", views.wig_home, name="wig-home"),
    url(r"^wks-home/$", views.wks_home, name="wks-home"),
    url(r"^ww2-home/$", views.ww2_home, name="ww2-home"),
    url(r"^zdk-home/$", views.zdk_home, name="zdk-home"),
    url(r"^zoe-home/$", views.zoe_home, name="zoe-home"),
    url(r"^zol-home/$", views.zol_home, name="zol-home"),

    url(r"^bdo-home/$", views.bdo_home, name="bdo-home"),
    url(r"^ok-home/$", views.ok_home, name="ok-home"),
    url(r"^op-home/$", views.op_home, name="op-home"),
    url(r"^opz-home/$", views.opz_home, name="opz-home"),
    url(r"^po-home/$", views.po_home, name="po-home"),
    url(r"^sp-home/$", views.sp_home, name="sp-home"),
    url(r"^ssop-home/$", views.ssop_home, name="ssop-home"),

    url(r"^l-home/$", views.l_home, name="l-home"),
    url(r"^ll-home/$", views.ll_home, name="ll-home"),
    url(r"^lll-home/$", views.lll_home, name="lll-home"),
    url(r"^lv-home/$", views.lv_home, name="lv-home"),
    url(r"^v-home/$", views.v_home, name="v-home"),

    url(r"^wgl-home/$", views.wgl_home, name="wgl-home"),
    url(r"^wko-home/$", views.wko_home, name="wko-home"),
    url(r"^wl-home/$", views.wl_home, name="wl-home"),
    url(r"^wmm-home/$", views.wmm_home, name="wmm-home"),
    url(r"^wnl-home/$", views.wnl_home, name="wnl-home"),
    url(r"^wopl-home/$", views.wopl_home, name="wopl-home"),
    url(r"^wsl-home/$", views.wsl_home, name="wsl-home"),

    url(r"^bo-home/$", views.bo_home, name="bo-home"),
    url(r"^m-home/$", views.m_home, name="m-home"),
    url(r"^oz-home/$", views.oz_home, name="oz-home"),
    url(r"^wop-home/$", views.wop_home, name="wop-home"),
    url(r"^wpn-home/$", views.wpn_home, name="wpn-home"),
    url(r"^wps-home/$", views.wps_home, name="wps-home"),

    url(r"^gmo-home/$", views.gmo_home, name="gmo-home"),
    url(r"^wk1-home/$", views.wk1_home, name="wk1-home"),
    url(r"^wos-home/$", views.wos_home, name="wos-home"),
    url(r"^wpn1-home/$", views.wpn1_home, name="wpn1-home"),
    url(r"^zf-home/$", views.zf_home, name="zf-home"),
    url(r"^zp2-home/$", views.zp2_home, name="zp2-home"),

    url(r"^l1-home/$", views.l1_home, name="l1-home"),
    url(r"^ll2-home/$", views.ll2_home, name="ll2-home"),
    url(r"^lll3-home/$", views.lll3_home, name="lll3-home"),
    url(r"^lv4-home/$", views.lv4_home, name="lv4-home"),

    url(r"^wop1-home/$", views.wop1_home, name="wop1-home"),
    url(r"^wop2-home/$", views.wop2_home, name="wop2-home"),
    url(r"^woplll-home/$", views.woplll_home, name="woplll-home"),
    url(r"^woplv-home/$", views.woplv_home, name="woplv-home"),
    url(r"^wopv-home/$", views.wopv_home, name="wopv-home"),
    url(r"^wopvl-home/$", views.wopvl_home, name="wopvl-home"),

    url(r"^we1-home/$", views.we1_home, name="we1-home"),
    url(r"^wep1-home/$", views.wep1_home, name="wep1-home"),
    url(r"^wjp-home/$", views.wjp_home, name="wjp-home"),
    url(r"^wma-home/$", views.wma_home, name="wma-home"),

    url(r"^wism-home/$", views.wism_home, name="wism-home"),
    url(r"^wjpt-home/$", views.wjpt_home, name="wjpt-home"),
    url(r"^wrrn-home/$", views.wrrn_home, name="wrrn-home"),
    url(r"^zopp-home/$", views.zopp_home, name="zopp-home"),

    url(r"^ue-home/$", views.ue_home, name="ue-home"),
    url(r"^wd-home/$", views.wd_home, name="wd-home"),
    url(r"^ww1-home/$", views.ww1_home, name="ww1-home"),

    url(r"^czk-home/$", views.czk_home, name="czk-home"),
    url(r"^ktmk-home/$", views.ktmk_home, name="ktmk-home"),
    url(r"^poin-home/$", views.poin_home, name="poin-home"),
    url(r"^wcb-home/$", views.wcb_home, name="wcb-home"),
    url(r"^wrs-home/$", views.wrs_home, name="wrs-home"),
    url(r"^wso-home/$", views.wso_home, name="wso-home"),
    url(r"^wzk-home/$", views.wzk_home, name="wzk-home"),
    url(r"^zb-home/$", views.zb_home, name="zb-home"),

    url(r"^tk-home/$", views.tk_home, name="tk-home"),
    url(r"^wiz-home/$", views.wiz_home, name="wiz-home"),
    url(r"^wjre-home/$", views.wjre_home, name="wjre-home"),
    url(r"^wnm-home/$", views.wnm_home, name="wnm-home"),
    url(r"^wpe1-home/$", views.wpe1_home, name="wpe1-home"),
    url(r"^wze-home/$", views.wze_home, name="wze-home"),
    url(r"^zpe-home/$", views.zpe_home, name="zpe-home"),


    url(r"^bhp-department/$", views.bhp_department, name="bhp-department"),
    url(r"^bif-department/$", views.bif_department, name="bif-department"),
    url(r"^department/$", views.department, name="department"),
    url(r"^wesi-department/$", views.wesi_department, name="wesi-department"),
    url(r"^wk-department/$", views.wk_department, name="wk-department"),
    url(r"^wl-department/$", views.wl_department, name="wl-department"),
    url(r"^wnpp-department/$", views.wnpp_department, name="wnpp-department"),
    url(r"^woa-department/$", views.woa_department, name="woa-department"),
    url(r"^wrz-department/$", views.wrz_department, name="wrz-department"),
    url(r"^wzn-department/$", views.wzn_department, name="wzn-department"),
    url(r"^wzp-department/$", views.wzp_department, name="wzp-department"),
    url(r"^zp-department/$", views.zp_department, name="zp-department"),
    url(r"^zuit-department/$", views.zuit_department, name="zuit-department"),

    url(r"^gkm-department/$", views.gkm_department, name="gkm-department"),
    url(r"^wb-department/$", views.wb_department, name="wb-department"),
    url(r"^wk2-department/$", views.wk2_department, name="wk2-department"),
    url(r"^wp-department/$", views.wp_department, name="wp-department"),
    url(r"^wrp-department/$", views.wrp_department, name="wrp-department"),

    url(r"^a-department/$", views.a_department, name="a-department"),

planner4u/models.py
from django.db import models

planner4u/templates/planner4u/dp-report/wop1-menu.html
{% extends 'planner4u/base.html' %}
{% block content %}

<style>
a.button1 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 90.5px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button1:active {
  box-shadow: none;
}

a.button1:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
a.button2 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 45.5px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button2:active {
  box-shadow: none;
}

a.button2:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
a.button3 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 116px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button3:active {
  box-shadow: none;
}

a.button3:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}

a.button4 {
  position: fixed;
  bottom: 65;
  right: 0;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: .8em 2em;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button4:active {
  box-shadow: none;
}

a.button4:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
</style>

<div class="content">
    <a href="{% url 'planner4u:wop1-department' %}" class="button1">Raport dla Departamenta w wybranym okresie</a><br>
    <a href="{% url 'planner4u:wop1-report' %}" class="button2">Raport dla wszystkich Departamentów w wybranym okresie</a><br>
    <a href="{% url 'planner4u:wop1-main' %}" class="button3">Raport dla wszystkich Departamentów</a>

    <a href="{% url 'planner4u:wop1-home' %}" class="button4">Powrót do Wydziału</a>
</div>

<footer>
    <div class="footer">
        <div class="footer-middle">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
          <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
          <link rel="stylesheet" type="text/css" href="footer.css">
              <div class="w3hubs-icon">
                  <a href="https://www.youtube.com/ministerstwoklimatui%C5%9Brodowiska" target="black"><i class="fa fa-youtube-play"></i></a>
                  <a href="https://twitter.com/MKiS_GOV_PL" target="black"><i class="fa fa-twitter"></i></a>
                  <a href="https://www.facebook.com/MKiSGOVPL" target="black"><i class="fa fa-facebook"></i></a>
                  <a href="https://www.instagram.com/mkis_gov_pl/" target="black"><i class="fa fa-instagram"></i></a>
                  <a href="https://www.linkedin.com/company/ministerstwo-klimatu/?viewAsMember=true" target="black"><i class="fa fa-linkedin"></i></a>
              </div>
        </div>
    </div>
</footer>

<style>
div.content {
    height: 10em;
    position: relative;
}
div.content .button1{
    margin: 0;
    position: absolute;
    top: 110%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
div.content .button2{
    margin: 0;
    position: absolute;
    top: 150%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
div.content .button3{
    margin: 0;
    position: absolute;
    top: 190%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
</style>

<style>
.footer {
    overflow: hidden;
    background-color: #00A499;
    padding: 20px 10px;
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
}

.footer-middle {
    text-align: center;
}

.footer a {
    color: white;
    text-align: center;
    padding: 28px;
    text-decoration: none;
    font-size: 18px;
    line-height: 25px;
}

.active:hover {
    background-color: white;
}

.footer a:hover {
    background-color: #28d8b2;
    color: white;
}

.footer a.active {
    background-color: white;
    color: white;
}

.footer-middle {
    text-align: center;
}

@media screen and (max-width: 500px) {
    .footer a {
        float: none;
        display: block;
        text-align: left;
    }
    .footer-middle {
        float: none;
    }
}
</style>

<style>
.w3hubs-icon{
	width: 100%;
	height: auto;
	margin: auto;
}

.w3hubs-icon ul{
	margin: 0px;
	text-align: center;
}

.w3hubs-icon ul li{
	display: inline-block;
	width: 50px;
	height: 50px;
	margin: 0px 10px;
	background: #7DCEA0;
}

.w3hubs-icon ul li a{
	text-decoration: none;
	color: #272727;
	font-size: 25px;
	display: block;
}

.w3hubs-icon ul li a i{
	line-height: 50px;
}

.w3hubs-icon ul li:hover{
	background: #e67e22;
}

.w3hubs-icon ul li a i {
    line-height: 38px;
}

.w3hubs-icon ul li a{
	font-size: 20px;
}

.w3hubs-icon ul li{
    width: 40px;
    height: 40%;
}
</style>

{% endblock %}

planner4u/templates/planner4u/dp-report/wop2-menu.html
{% extends 'planner4u/base.html' %}
{% block content %}

<style>
a.button1 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 90.5px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button1:active {
  box-shadow: none;
}

a.button1:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
a.button2 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 45.5px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button2:active {
  box-shadow: none;
}

a.button2:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
a.button3 {
  cursor: pointer;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: 10px 116px;
  justify-content: space-between;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button3:active {
  box-shadow: none;
}

a.button3:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}

a.button4 {
  position: fixed;
  bottom: 65;
  right: 0;
  color: white;
  font-weight: bold;
  text-decoration: none;
  user-select: none;
  padding: .8em 2em;
  outline: none;
  background-color: #28d8b2;
  background-image: linear-gradient(45deg, rgba(0,0,0,.0) 30%, rgba(255,255,255,.8), rgba(255,255,255,.0) 70%), radial-gradient(0% 0% at 50% 0%, rgba(255,255,255,.7) 0%, rgba(255,255,255,.5) 50%, rgba(0,0,0,0) 50%);
  background-repeat: no-repeat;
  background-size: 200% 100%, auto;
  background-position: 200% 0, 0 0;
}

a.button4:active {
  box-shadow: none;
}

a.button4:hover {
  transition: .5s linear;
  background-position: -200% 0, 0 0;
}
</style>

<div class="content">
    <a href="{% url 'planner4u:wop2-department' %}" class="button1">Raport dla Departamenta w wybranym okresie</a><br>
    <a href="{% url 'planner4u:wop2-report' %}" class="button2">Raport dla wszystkich Departamentów w wybranym okresie</a><br>
    <a href="{% url 'planner4u:wop2-main' %}" class="button3">Raport dla wszystkich Departamentów</a>

    <a href="{% url 'planner4u:wop2-home' %}" class="button4">Powrót do Wydziału</a>
</div>

<footer>
    <div class="footer">
        <div class="footer-middle">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
          <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
          <link rel="stylesheet" type="text/css" href="footer.css">
              <div class="w3hubs-icon">
                  <a href="https://www.youtube.com/ministerstwoklimatui%C5%9Brodowiska" target="black"><i class="fa fa-youtube-play"></i></a>
                  <a href="https://twitter.com/MKiS_GOV_PL" target="black"><i class="fa fa-twitter"></i></a>
                  <a href="https://www.facebook.com/MKiSGOVPL" target="black"><i class="fa fa-facebook"></i></a>
                  <a href="https://www.instagram.com/mkis_gov_pl/" target="black"><i class="fa fa-instagram"></i></a>
                  <a href="https://www.linkedin.com/company/ministerstwo-klimatu/?viewAsMember=true" target="black"><i class="fa fa-linkedin"></i></a>
              </div>
        </div>
    </div>
</footer>

<style>
div.content {
    height: 10em;
    position: relative;
}
div.content .button1{
    margin: 0;
    position: absolute;
    top: 110%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
div.content .button2{
    margin: 0;
    position: absolute;
    top: 150%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
div.content .button3{
    margin: 0;
    position: absolute;
    top: 190%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%)
}
</style>

<style>
.footer {
    overflow: hidden;
    background-color: #00A499;
    padding: 20px 10px;
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
}

.footer-middle {
    text-align: center;
}

.footer a {
    color: white;
    text-align: center;
    padding: 28px;
    text-decoration: none;
    font-size: 18px;
    line-height: 25px;
}

.active:hover {
    background-color: white;
}

.footer a:hover {
    background-color: #28d8b2;
    color: white;
}

.footer a.active {
    background-color: white;
    color: white;
}

.footer-middle {
    text-align: center;
}

@media screen and (max-width: 500px) {
    .footer a {
        float: none;
        display: block;
        text-align: left;
    }
    .footer-middle {
        float: none;
    }
}
</style>

<style>
.w3hubs-icon{
	width: 100%;
	height: auto;
	margin: auto;
}

.w3hubs-icon ul{
	margin: 0px;
	text-align: center;
}

.w3hubs-icon ul li{
	display: inline-block;
	width: 50px;
	height: 50px;
	margin: 0px 10px;
	background: #7DCEA0;
}

.w3hubs-icon ul li a{
	text-decoration: none;
	color: #272727;
	font-size: 25px;
	display: block;
}

.w3hubs-icon ul li a i{
	line-height: 50px;
}

.w3hubs-icon ul li:hover{
	background: #e67e22;
}

.w3hubs-icon ul li a i {
    line-height: 38px;
}

.w3hubs-icon ul li a{
	font-size: 20px;
}

.w3hubs-icon ul li{
    width: 40px;
    height: 40%;
}
</style>

{% endblock %}